'use strict';
const C=window.SURVEY_CONFIG,S=window.SurveyCore,$=s=>document.querySelector(s),KEY='clinic-survey-draft-v1';
let step=0,started=Date.now(),frozen=null,sent=false,busy=false,timer=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n===null?'資料不足':Math.round(n).toLocaleString('zh-TW');
const ready=()=>/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(C.endpoint)&&!!C.organizer.trim()&&!!C.contact.trim()&&!!C.retention.trim();
$('#mode').textContent=ready()?'正式調查：填答完成後，由您確認才送出。':'預覽模式：尚未設定正式收件端與主辦資訊。可試填及查看儀表板，不會傳送資料。';
for(const k of ['organizer','contact','retention'])$('#'+k).textContent=C[k]||'正式開放前由主辦單位填寫';$('#purpose').textContent=C.purpose;
const hints={district:'例如：板橋區、竹東鎮；不用填地址。',patients:'一天合計幾人次？含各時段；不是不重複病人人數。',days:'一個月約開幾天？同一天多診只算一天。',doctors:'目前實際參與看診的醫師人數。',staff:'護理、行政、藥事等人員合計；不用換算全職。',period:'以下費用及工時所代表的月份。',purchase:'每月藥品、醫材及耗材合計。不含設備。',it:'每月 HIS、軟體、維護、資安與 IT 外包合計。',admin:'每月行政人員薪資與行政外包合計。臨床／行政兼任者只估行政部分。',hours:'全診所每週處理申報、文書、採購與 IT 的總工時；兩人各 5 小時就填 10。',services:'至少選一項想了解或需要的服務；不代表願意加入。',conditions:'可複選，不限項數。',fee:'全部中心服務合計，每家每月願付上限。只接受免費請填 0。',expectedSaving:'原採購＋IT＋行政支出，期待少幾 %？尚未扣除中心月費；不知道可留白。',expectedHours:'每週行政與 IT 工時，期待少幾 %？不知道可留白。',note:'選填；請勿填病人、診所名稱或聯絡個資。'};
const basic=['county','district','type','specialty','role','patients','days','doctors','staff'],baseline=['period','quality','purchase','it','admin','hours','his'];
for(const [k,label,type,required,min,max] of S.fields){const parent=basic.includes(k)?'basic':baseline.includes(k)?'baseline':'expectations';const wrap=document.createElement(type==='multi'?'fieldset':'div');wrap.className='field'+(['multi','text'].includes(type)&&k!=='district'?' wide':'');
const title=esc(label)+(required?' <span aria-label="必填">*</span>':' <span class="optional">選填／可留白</span>');
if(type==='multi'){wrap.innerHTML=`<legend>${title}</legend><div class="choices">${S.options[k].map((v,i)=>`<label><input type="checkbox" name="${k}" value="${esc(v)}">${esc(v)}</label>`).join('')}</div>`;}
else {let input=type==='enum'?`<select id="${k}" name="${k}"><option value="">請選擇</option>${S.options[k].map(v=>`<option>${esc(v)}</option>`).join('')}</select>`:k==='note'?`<textarea id="${k}" name="${k}" rows="3" maxlength="500"></textarea>`:`<input id="${k}" name="${k}" type="${type==='number'?'number':type==='month'?'month':'text'}" ${type==='number'?`min="${min}" max="${max}" step="1" inputmode="numeric"`:`maxlength="${min||30}"`} ${type==='month'?`max="${new Date().toISOString().slice(0,7)}"`:''}>`;wrap.innerHTML=`<label for="${k}">${title}</label>${input}`;}
if(hints[k])wrap.insertAdjacentHTML('beforeend',`<small id="hint-${k}">${esc(hints[k])}</small>`);$('#'+parent).append(wrap);const el=$('#'+k);if(el){el.required=required;if(hints[k])el.setAttribute('aria-describedby','hint-'+k);}}
function specialty(){const type=$('#type').value;for(const o of $('#specialty').options){o.hidden=!!o.value&&(type==='中醫'?!o.value.startsWith('中醫'):type==='牙醫'?!o.value.includes('牙'):type==='西醫'?(o.value.startsWith('中醫')||o.value.includes('牙')):false);}if($('#specialty').selectedOptions[0]?.hidden)$('#specialty').value='';}
$('#type').addEventListener('change',specialty);
function answers(){const a={};for(const [k,,type] of S.fields){if(type==='multi')a[k]=Array.from(document.querySelectorAll(`input[name="${k}"]:checked`),e=>e.value);else{const v=$('#'+k).value.trim();a[k]=type==='number'?(v===''?null:Number(v)):(v||null);}}return a;}
function restore(a){for(const [k,,type] of S.fields){if(type==='multi')document.querySelectorAll(`input[name="${k}"]`).forEach(e=>e.checked=(a[k]||[]).includes(e.value));else $('#'+k).value=a[k]??'';}specialty();}
function save(){try{if($('#remember').checked&&!sent)localStorage.setItem(KEY,JSON.stringify({answers:answers(),consent:$('#consent').checked,started,frozen}));else localStorage.removeItem(KEY);}catch{$('#errors').textContent='此瀏覽器無法暫存；請下載紀錄後再離開。';}}
try{const raw=localStorage.getItem(KEY);if(raw){const d=JSON.parse(raw);restore(d.answers||{});$('#consent').checked=!!d.consent;$('#remember').checked=true;started=d.started||Date.now();frozen=d.frozen||null;}}catch{}
function errorsFor(s){if(s===0)return $('#consent').checked?[]:['請閱讀並勾選自願參與同意聲明。'];const ids=s===1?basic:s===2?baseline:S.fields.map(x=>x[0]).filter(k=>!basic.includes(k)&&!baseline.includes(k));return S.validate(answers()).filter(e=>ids.some(k=>e.startsWith(S.fields.find(f=>f[0]===k)[1])));}
function move(to){step=to;document.querySelectorAll('.step').forEach((e,i)=>e.hidden=i!==step);document.querySelectorAll('.steps span').forEach((e,i)=>{e.classList.toggle('active',i===step);if(i===step)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});$('#back').hidden=step===0;$('#next').hidden=step===4;$('#back').disabled=!!frozen;$('#progress').textContent=`第 ${step+1} / 5 步`;$('#errors').textContent='';if(step===4)render();window.scrollTo({top:0,behavior:'smooth'});}
$('#next').onclick=()=>{const errors=errorsFor(step);if(errors.length){$('#errors').textContent=errors.join('\n');$('#errors').focus();return;}move(step+1);};$('#back').onclick=()=>move(step-1);
$('#survey').addEventListener('submit',e=>e.preventDefault());$('#survey').addEventListener('input',save);$('#remember').onchange=save;
function render(){const a=answers();const initialFee=a.fee;$('#dashboard').innerHTML=`<div class="notice">這裡只比較支援費用，不代表診所總成本、利潤或醫療品質。已填 ${['purchase','it','admin','expectedSaving','expectedHours','hours'].filter(k=>a[k]!==null).length}/6 項主要試算資料；未提供項目不補零。</div><div class="field"><label for="scenario-fee">試算中心月費（元）</label><input id="scenario-fee" type="number" min="0" max="1000000" step="1" value="${initialFee??''}"><small>起始值採您願付上限；可另填情境月費，不會修改原答案。實際中心報價仍未知。</small></div><div id="metrics"></div><div class="notice"><strong>規劃研究會如何使用？</strong><p>綜合不同區域、類別與科別的意願、願付費及支援支出，評估潛在參與群體。單一中心的固定、人力及建置成本仍需另取報價；單份問卷不能推算最佳中心規模。</p></div>`;
function draw(){const raw=$('#scenario-fee').value;const fee=raw!==''&&$('#scenario-fee').validity.valid?Number(raw):null;const m=S.scenario(a,fee);const max=Math.max(m.base||0,m.after||0,1);const bar=(name,value,after)=>`<div><div class="bar-label"><span>${name}</span><strong>${money(value)} 元／月</strong></div><div class="bar ${after?'after':''}"><i style="width:${value===null?0:value/max*100}%"></i></div></div>`;
$('#metrics').innerHTML=`<div class="cards"><div class="metric"><span>期待支援費淨${m.net!==null&&m.net<0?'增加':'節省'}</span><b>${money(m.net===null?null:Math.abs(m.net))}</b><small>元／月，已扣試算中心費</small></div><div class="metric"><span>期待每週支援工時</span><b>${m.hoursAfter===null?'資料不足':m.hoursAfter.toFixed(1)}</b><small>小時；目前 ${m.hoursBefore===null?'未提供':m.hoursBefore+' 小時'}</small></div><div class="metric"><span>估計每月看診量</span><b>${money(m.monthlyVisits)}</b><small>人次；每日人次 × 開診天數</small></div></div><div class="bars">${bar('目前支援費',m.base,false)}${bar('依期待設定調整後（含月費）',m.after,true)}</div><p class="${m.net!==null&&m.net<0?'warn':'small'}">${m.net===null?'請提供三項支援費、期待減少比例及試算月費，才能計算費用差額。':m.net<0?'在這組期待下，中心費高於可省支援費，每月支出反而增加。':'此結果成立的前提是您填寫的節省期待可實現，並非實測。'}</p><p>按您的期待，損益平衡中心月費為 <strong>${money(m.gross)} 元</strong>。這是可省下的原支援費，並非中心能提供的報價。</p><details><summary>如何計算？</summary><p>原支援費＝採購＋IT＋行政。期待節省＝原支援費×期待減少比例。情境費用＝原支援費−期待節省＋試算月費。工時＝原工時×（1−期待減少比例）。不加上舊模擬器的示範折扣，不把期待當成實證。</p></details>`;}
$('#scenario-fee').addEventListener('input',draw);draw();$('#review').innerHTML=S.fields.map(([k,l])=>`<dt>${esc(l)}</dt><dd>${esc(Array.isArray(a[k])?(a[k].join('、')||'未選擇'):a[k]??'未提供')}</dd>`).join('');$('#submit').disabled=!ready()||sent||busy;$('#submit').textContent=sent?'已送出':frozen?'重試同一份送出':'同意並送出問卷';}
const uuid=()=>crypto.randomUUID?crypto.randomUUID():([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));
$('#submit').onclick=()=>{
 if(!ready()||busy||sent)return;const a=answers();const errors=S.validate(a);if(!$('#consent').checked)errors.push('缺少同意聲明');if(errors.length){$('#errors').textContent=errors.join('\n');return;}
 if(!frozen)frozen={surveyVersion:C.surveyVersion,consentVersion:C.consentVersion,submissionId:uuid(),receiptToken:uuid(),consent:true,clientSubmittedAt:new Date().toISOString(),elapsedSeconds:Math.round((Date.now()-started)/1000),origin:location.origin,answers:a,website:''};
 busy=true;$('#submit').disabled=true;$('#back').disabled=true;$('#clear').disabled=true;$('#submit-status').textContent='送出中，請等候儲存確認…';save();
 const form=document.createElement('form');form.method='POST';form.action=C.endpoint;form.target='submission-receipt';const input=document.createElement('input');input.type='hidden';input.name='payload';input.value=JSON.stringify(frozen);form.append(input);document.body.append(form);form.submit();form.remove();
 timer=setTimeout(()=>{busy=false;$('#submit').disabled=false;$('#clear').disabled=false;$('#submit').textContent='重試同一份送出';$('#submit-status').textContent='尚未收到儲存確認；資料可能已寫入，請勿重新填寫。可重試同一份送出（相同編號不重複記錄）。\n編號：'+frozen.submissionId;},30000);
};
window.addEventListener('message',event=>{if(!frozen||sent)return;const trusted=event.origin==='https://script.google.com'||/^https:\/\/[a-z0-9-]+\.googleusercontent\.com$/.test(event.origin);const d=event.data;if(!trusted||!d||d.type!=='clinic-survey-receipt'||d.submissionId!==frozen.submissionId||d.receiptToken!==frozen.receiptToken)return;clearTimeout(timer);busy=false;$('#clear').disabled=false;if(d.ok){sent=true;$('#submit-status').textContent='已確認存入資料表。感謝您的參與！\n送出編號：'+frozen.submissionId+'\n如需撤回，請向主辦單位提供此編號。';try{localStorage.removeItem(KEY);}catch{}}else{$('#submit-status').textContent='未完成儲存：'+(d.message||'請稍後重試或聯絡主辦單位。');}render();});
$('#download').onclick=()=>{const body=JSON.stringify({surveyVersion:C.surveyVersion,consent:$('#consent').checked,consentVersion:C.consentVersion,status:sent?'confirmed':frozen?'unconfirmed':'not_submitted',submissionId:frozen?.submissionId||null,answers:answers()},null,2);const u=URL.createObjectURL(new Blob([body],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='診所填答紀錄.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('#clear').onclick=()=>{if(!confirm('清除本機填答？此動作不會刪除已送至主辦單位的資料。'))return;try{localStorage.removeItem(KEY);}catch{}$('#survey').reset();$('#remember').checked=false;frozen=null;sent=false;busy=false;started=Date.now();clearTimeout(timer);$('#submit-status').textContent='';move(0);};
move(frozen?4:0);
