const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),http=require('http'),path=require('path');const {chromium}=require('playwright');
const root=__dirname;const ctx={console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'schema.js'),'utf8'),ctx);const S=ctx.SurveyCore;
const a={county:'新北市',district:'板橋區',type:'西醫',specialty:'家庭醫學科',role:'負責醫師／經營者',patients:80,days:24,doctors:2,staff:4,period:'2026-08',quality:'依經驗估計',purchase:80000,it:18000,admin:80000,hours:40,his:'已有 HIS，能否交換資料不清楚',services:['耗材共同採購'],willingness:'符合條件才加入',conditions:['保留臨床自主'],fee:20000,expectedSaving:20,expectedHours:25,standard:'願意但須保留例外',fhir:'願意，但須先確認資料範圍與責任',insurance:'有條件參與，須保障臨床自主與資料權限',note:'=IMPORTXML("x")'};
assert.equal(S.validate(a).length,0);assert.equal(S.scenario(a,20000).net,15600);assert.equal(S.scenario(a,20000).hoursAfter,30);assert.equal(S.scenario({...a,it:null},20000).net,null);assert.equal(S.scenario({...a,purchase:0,it:0,admin:0},0).net,0);assert(S.validate({...a,expectedSaving:101}).length);assert(S.validate({...a,district:' '}).length);console.log('PASS model: missing vs zero, units, numeric bounds, required validation');
let rows=[],headers;let released=0;const gas={console,ContentService:{createTextOutput:x=>x},HtmlService:{XFrameOptionsMode:{ALLOWALL:'all'},createHtmlOutput:x=>({html:x,setXFrameOptionsMode(){return this;}})},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){released++;}})},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'sheet'})},SpreadsheetApp:{flush(){},openById:()=>({getSheetByName:()=>({getLastRow:()=>rows.length+1,getRange:(r,c)=>r===1?{getValues:()=>[headers]}:{createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.some(x=>x[1]==="'"+id)})})},appendRow:r=>rows.push(r)})})}};
vm.createContext(gas);let code=fs.readFileSync(path.join(root,'Code.gs'),'utf8').replace("['https://YOUR_ACCOUNT.github.io']","['https://test.github.io']").replace("organizer: '',contact: '',retention: ''","organizer: '測試',contact: 'test@example.com',retention: '12個月'");vm.runInContext(code,gas);headers=vm.runInContext('META.concat(SurveyCore.fields.map(f=>f[0]))',gas);
const payload={origin:'https://test.github.io',submissionId:'11111111-1111-4111-8111-111111111111',receiptToken:'22222222-2222-4222-8222-222222222222',consent:true,consentVersion:'2026-09-23-v1',surveyVersion:'clinic-survey-1.0',answers:a,elapsedSeconds:350};
const post=p=>gas.doPost({parameter:{payload:JSON.stringify(p)}}).html;
assert.match(post({...payload,consent:false}),/"ok":false/);assert.equal(rows.length,0);assert.match(post(payload),/"ok":true/);assert.equal(rows.length,1);assert.equal(rows[0].at(-1),"'"+a.note);post(payload);assert.equal(rows.length,1);assert(released>=2);assert.match(post({...payload,origin:'https://evil.test'}),/"ok":false/);assert.match(post({...payload,answers:{...a,fee:NaN}}),/"ok":true/); // JSON NaN becomes null, allowed optional value; same ID remains deduped.
console.log('PASS backend mock: consent, schema, origin config, sheet escaping, receipt, lock and idempotency');
(async()=>{const server=http.createServer((req,res)=>{const n=req.url==='/'?'index.html':req.url.slice(1);if(!['index.html','styles.css','app.js','schema.js','config.js'].includes(n)&&!/^fonts\/[a-z0-9-]+\.woff2?$/.test(n)){res.writeHead(404);res.end();return;}res.setHeader('content-type',n.endsWith('.woff2')?'font/woff2':n.endsWith('.woff')?'font/woff':n.endsWith('.js')?'text/javascript':n.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,n)));});await new Promise(r=>server.listen(4189,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/tmp/chromium',args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});const page=await browser.newPage({viewport:{width:1280,height:950}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4189');await page.click('#next');assert.match(await page.locator('#errors').innerText(),/同意/);await page.check('#consent');await page.click('#next');await page.click('#next');assert.match(await page.locator('#errors').innerText(),/縣市/);
for(const [k,,t] of S.fields){if(a[k]===undefined||t==='multi')continue;await page.locator('#'+k).evaluate((e,v)=>{e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));},a[k]);}await page.locator('input[name=services]').first().evaluate(e=>e.checked=true);await page.click('#next');await page.click('#next');await page.click('#next');assert.match(await page.locator('#metrics').innerText(),/15,600/);assert.match(await page.locator('#metrics').innerText(),/30.0/);assert(await page.locator('#submit').isDisabled());await page.fill('#scenario-fee','50000');assert.match(await page.locator('#metrics').innerText(),/增加/);assert.equal(await page.locator('#fee').inputValue(),'20000');assert.match(await page.locator('#review').textContent(),/=IMPORTXML/);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(root,'dashboard-preview.png'),fullPage:true});
await page.check('#remember');await page.reload();assert.equal(await page.locator('#county').inputValue(),'新北市');await page.locator('#clear').evaluate(el=>{window.confirm=()=>true;el.click();});assert.equal(await page.locator('#county').inputValue(),'');assert.equal(await page.evaluate(()=>localStorage.getItem('clinic-survey-draft-v1')),null);
for(const w of [1280,375]){await page.setViewportSize({width:w,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.screenshot({path:path.join(root,'mobile-preview.png'),fullPage:true});assert.equal(errors.length,0);
// Confirmed receipt and wrong-origin rejection in a configured, intercepted POST environment.
await page.route('**/config.js',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'config.js'),'utf8').replace("endpoint: ''","endpoint: 'https://script.google.com/macros/s/TEST/exec'").replace("organizer: ''","organizer: '測試單位'").replace("contact: ''","contact: 'test@example.com'").replace("retention: ''","retention: '12個月'")}));let captured;await page.route('https://script.google.com/**',async route=>{captured=JSON.parse(new URLSearchParams(route.request().postData()).get('payload'));await route.fulfill({contentType:'text/html',body:'<p>Test transport</p>'});});await page.reload();await page.check('#consent');await page.evaluate(a=>restore(a),a);await page.evaluate(()=>move(4));await page.click('#submit');await page.waitForTimeout(300);assert(captured);const receipt={type:'clinic-survey-receipt',submissionId:captured.submissionId,receiptToken:captured.receiptToken,ok:true};await page.evaluate(d=>window.dispatchEvent(new MessageEvent('message',{origin:'https://evil.test',data:d})),receipt);assert(!/已確認/.test(await page.locator('#submit-status').innerText()));await page.evaluate(d=>window.dispatchEvent(new MessageEvent('message',{origin:'https://script.google.com',data:d})),receipt);assert.match(await page.locator('#submit-status').innerText(),/已確認/);assert(await page.locator('#submit').isDisabled());assert(await page.locator('#back').isDisabled());assert.equal(captured.answers.fee,20000);assert.equal(errors.length,0);
await browser.close();server.close();console.log('PASS browser: consent gate, required fields, dashboard, fee isolation, draft/clear, mobile, mocked POST/receipt, wrong origin and no runtime errors');})().catch(e=>{console.error(e);process.exit(1)});
